from datetime import datetime, timezone

from langchain_core.tools import tool

_REPORT_TEMPLATE = """\
# {title}

> *Generated by LangChain DeepAgent &middot; {timestamp}*

---

{content}

---

*This report was automatically generated. Please verify all facts and sources independently.*
"""

_SECTION_GUIDE = """
## Executive Summary

{executive_summary}

## Key Findings

{key_findings}

## Analysis

{analysis}

## Conclusion

{conclusion}
"""


@tool
def write_report(
    title: str,
    executive_summary: str,
    key_findings: str,
    analysis: str,
    conclusion: str,
) -> str:
    """
    Format research findings into a professional structured markdown report.

    Use this skill AFTER gathering all information via web_search and think.
    Pass the findings as structured sections; the tool handles all formatting.

    Args:
        title:             Concise, descriptive report title.
        executive_summary: 2-3 sentence high-level overview of the topic and findings.
        key_findings:      Bullet-point list of the most important facts (with sources).
        analysis:          Deeper discussion synthesising the findings.
        conclusion:        Actionable takeaways and recommendations.

    Returns:
        A fully formatted markdown report ready to present to the user.
    """
    timestamp = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    body = _SECTION_GUIDE.format(
        executive_summary=executive_summary.strip(),
        key_findings=key_findings.strip(),
        analysis=analysis.strip(),
        conclusion=conclusion.strip(),
    )

    return _REPORT_TEMPLATE.format(
        title=title.strip(),
        timestamp=timestamp,
        content=body.strip(),
    )
